
CREATE TABLE `player` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `adminlevel` int(11) NOT NULL DEFAULT 0,
  `money` int(11) NOT NULL DEFAULT 0,
  `bank_money` int(11) NOT NULL DEFAULT 0,
  `level` int(11) NOT NULL DEFAULT 0,
  `spawnchange` int(11) NOT NULL DEFAULT 0,
  `job` int(11) NOT NULL DEFAULT 0,
  `jobskills` varchar(255) NOT NULL DEFAULT "",
  `jailtime` int(11) NOT NULL DEFAULT 0,
  `jailtime_reduce` int(11) NOT NULL DEFAULT 0,
  `uni_points` int(11) NOT NULL DEFAULT 0,
  `uni_economy` int(11) NOT NULL DEFAULT 0,
  `uni_business` int(11) NOT NULL DEFAULT 0,
  `uni_workaholic` int(11) NOT NULL DEFAULT 0,
  `perso` int(11) NOT NULL DEFAULT 0,
  `donator` int(11) NOT NULL DEFAULT 0,
  `deadtime` int(11) NOT NULL DEFAULT 0,
  `fspawn` int(11) NOT NULL DEFAULT 0,
  `hasPed` varchar(255) NOT NULL DEFAULT "",
  `timeban` int(11) NOT NULL DEFAULT 0,
  `ausschluss` int(11) NOT NULL DEFAULT 0,
  `job_skills` varchar(255) NOT NULL DEFAULT "",
  `warns` int(11) NOT NULL DEFAULT 0,
  `Hwid` varchar(255) NOT NULL DEFAULT "",
  `fgehalt` int(11) NOT NULL DEFAULT 0,
  `paycheck` int(11) NOT NULL DEFAULT 0,
  `handy` int(11) NOT NULL DEFAULT 0,
  `guthaben` int(11) NOT NULL DEFAULT 0,
  `married` int(11) NOT NULL DEFAULT 0,
  `grade` int(11) NOT NULL DEFAULT 0,
  `food` int(11) NOT NULL DEFAULT 0,
  `drink` int(11) NOT NULL DEFAULT 0,
  `zwd` int(11) NOT NULL DEFAULT 0,
  `duty` tinyint(1) NOT NULL DEFAULT 0,
  `is_cuffed` tinyint(1) NOT NULL DEFAULT 0,
  `is_tied` tinyint(1) NOT NULL DEFAULT 0,
  `hp` int(11) NOT NULL DEFAULT 100,
  `armor` int(11) NOT NULL DEFAULT 0,
  `pos_x` float NOT NULL DEFAULT 0,
  `pos_y` float NOT NULL DEFAULT 0,
  `pos_z` float NOT NULL DEFAULT 0,
  `pos_heading` float NOT NULL DEFAULT 0,
  `dimension` int(11) NOT NULL DEFAULT 0,
  `SCName` varchar(255) NOT NULL DEFAULT "",
  `weapons` text NOT NULL,
  `weapon_components` text NOT NULL,
  `wallpaperId` int(11) NOT NULL DEFAULT 0,
  `klingeltonId` int(11) NOT NULL DEFAULT 0,
  `team_id` int(11) NOT NULL DEFAULT 0,
  `team_rank` int(11) NOT NULL DEFAULT 0,
  `death_status` int(11) NOT NULL DEFAULT 0,
  `swat` int(11) NOT NULL DEFAULT 0,
  `uhaft_time` int(11) NOT NULL DEFAULT 0,
  `einwanderung` int(11) NOT NULL DEFAULT 0,
  `swat_duty` int(11) NOT NULL DEFAULT 0,
  `teamfight` int(11) NOT NULL DEFAULT 0,
  `paintball` int(11) NOT NULL DEFAULT 0,
  `suspension` int(11) NOT NULL DEFAULT 0,
  `blackmoney` int(11) NOT NULL DEFAULT 0,
  `blackmoneybank` int(11) NOT NULL DEFAULT 0,
  `payday` int(11) NOT NULL DEFAULT 0,
  `rp` int(11) NOT NULL DEFAULT 0,
  `ownHouse` int(11) NOT NULL DEFAULT 0,
  `wanteds` int(11) NOT NULL DEFAULT 0,
  `Lic_Car` int(11) NOT NULL DEFAULT 0,
  `Lic_LKW` int(11) NOT NULL DEFAULT 0,
  `Lic_Bike` int(11) NOT NULL DEFAULT 0,
  `Lic_PlaneA` int(11) NOT NULL DEFAULT 0,
  `Lic_PlaneB` int(11) NOT NULL DEFAULT 0,
  `Lic_Boot` int(11) NOT NULL DEFAULT 0,
  `Lic_Taxi` int(11) NOT NULL DEFAULT 0,
  `Lic_Gun` int(11) NOT NULL DEFAULT 0,
  `Lic_Hunting` int(11) NOT NULL DEFAULT 0,
  `Lic_Biz` int(11) NOT NULL DEFAULT 0,
  `Lic_FirstAID` int(11) NOT NULL DEFAULT 0,
  `lic_transfer` int(11) NOT NULL DEFAULT 0,
  `tax_sum` int(11) NOT NULL DEFAULT 0,
  `dead_x` float NOT NULL DEFAULT 0,
  `dead_y` float NOT NULL DEFAULT 0,
  `dead_z` float NOT NULL DEFAULT 0,
  `online` tinyint(1) NOT NULL DEFAULT 0,
  `lastSaved` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vehicles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `model` int(11) NOT NULL,
  `owner` int(11) NOT NULL,
  `color1` int(11) NOT NULL,
  `color2` int(11) NOT NULL,
  `fuel` int(11) NOT NULL,
  `tuning` text NOT NULL,
  `zustand` int(11) NOT NULL,
  `neon` varchar(255) NOT NULL DEFAULT "",
  `km` float NOT NULL,
  `plate` varchar(255) NOT NULL,
  `gps_tracker` tinyint(1) NOT NULL DEFAULT 0,
  `registered` tinyint(1) NOT NULL DEFAULT 0,
  `TuningState` tinyint(1) NOT NULL DEFAULT 0,
  `WheelClamp` int(11) NOT NULL DEFAULT 0,
  `alarm_system` tinyint(1) NOT NULL DEFAULT 0,
  `inGarage` tinyint(1) NOT NULL DEFAULT 0,
  `garage_id` int(11) NOT NULL,
  `vgarage` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fvehicles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `team` int(11) NOT NULL,
  `model` int(11) NOT NULL,
  `color1` int(11) NOT NULL,
  `color2` int(11) NOT NULL,
  `fuel` int(11) NOT NULL,
  `tuning` text NOT NULL,
  `zustand` int(11) NOT NULL,
  `km` int(11) NOT NULL,
  `plate` varchar(255) NOT NULL,
  `gps_tracker` tinyint(1) NOT NULL DEFAULT 0,
  `registered` tinyint(1) NOT NULL DEFAULT 0,
  `WheelClamp` int(11) NOT NULL DEFAULT 0,
  `alarm_system` tinyint(1) NOT NULL DEFAULT 0,
  `inGarage` tinyint(1) NOT NULL DEFAULT 0,
  `pos_x` float NOT NULL DEFAULT 0,
  `pos_y` float NOT NULL DEFAULT 0,
  `pos_z` float NOT NULL DEFAULT 0,
  `lastGarage` int(11) NOT NULL,
  `defcon_level` int(11) NOT NULL DEFAULT 0,
  `planning_vehicle` int(11) NOT NULL DEFAULT 0,
  `carsell_price` int(11) NOT NULL DEFAULT 0,
  `vgarage` int(11) NOT NULL DEFAULT 0,
  `TuningState` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `houses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` int(11) NOT NULL,
  `price` int(11) NOT NULL,
  `interiorid` int(11) NOT NULL,
  `ownerID` int(11) NOT NULL,
  `owner` varchar(255) NOT NULL,
  `posX` float NOT NULL,
  `posY` float NOT NULL,
  `posZ` float NOT NULL,
  `colshapeX` float NOT NULL,
  `colshapeY` float NOT NULL,
  `colshapeZ` float NOT NULL,
  `heading` float NOT NULL,
  `maxrents` int(11) NOT NULL,
  `inv_cash` int(11) NOT NULL,
  `keller` int(11) NOT NULL,
  `moneykeller` int(11) NOT NULL,
  `garage` int(11) NOT NULL,
  `trash_amount` float NOT NULL,
  `dimension_null_house` tinyint(1) NOT NULL,
  `show_phonenumber` varchar(255) NOT NULL,
  `bl_amount` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `business` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `money` int(11) NOT NULL,
  `motd` text NOT NULL,
  `gov_register` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `business_members` (
  `business_id` int(11) NOT NULL,
  `player_id` int(11) NOT NULL,
  `manage` tinyint(1) NOT NULL,
  `money` tinyint(1) NOT NULL,
  `inventory` tinyint(1) NOT NULL,
  `gehalt` int(11) NOT NULL,
  `owner` tinyint(1) NOT NULL,
  `fuelstation` tinyint(1) NOT NULL,
  `raffinery` tinyint(1) NOT NULL,
  `nightclub` tinyint(1) NOT NULL,
  `tattoo` tinyint(1) NOT NULL,
  PRIMARY KEY (`business_id`,`player_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `weight` int(11) NOT NULL,
  `illegal` tinyint(1) NOT NULL,
  `script` varchar(255) NOT NULL,
  `me_message` varchar(255) NOT NULL,
  `maximum_stacksize` int(11) NOT NULL,
  `remove_on_use` tinyint(1) NOT NULL,
  `durability` int(11) NOT NULL,
  `durability_loss_min` int(11) NOT NULL,
  `type` int(11) NOT NULL,
  `image_path` varchar(255) NOT NULL,
  `restricted_to_teams` varchar(255) NOT NULL,
  `allowed_vehiclemodels` varchar(255) NOT NULL,
  `attachment_only_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
